name: Build & upload to Firebase App Distribution


'on':
  push:
    branches:
      #- feat*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #- name: fake local properties
       # run: echo "test" > android/local.properties
      #- name: build release
        #run: cd android && bash ./gradlew assembleRelease
    # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      # Build :D
      - run: flutter build apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk